"""PeachState CoolChain domain — GA crop thresholds, GDD, spoilage models.

Day 3: canopy heat risk engine, harvest timing alerts, Q10 spoilage
kinetics, and corridor routing comparison.
"""

from .canopy_risk import (
    CANOPY_CAP_F,
    EXCEEDANCE_FULL_H,
    GA_CROP_THRESHOLDS_F,
    PERSISTENCE_FULL_H,
    VPD_COOLING_C,
    RiskInputs,
    RiskResult,
    RiskTier,
    WorkerSafetyResult,
    canopy_heat_risk,
    canopy_risk_score,
    estimate_canopy_temp,
    normalized_temp_score,
    score_field_from_db,
    tier,
    vpd_kpa,
    worker_wbgt_subscore,
)
from .harvest_timing import (
    HARVEST_COOLDOWN_H,
    HARVEST_EXCEEDANCE_THRESHOLD_H,
    HARVEST_URGENCY_THRESHOLD,
    GA_CROP_GDD,
    HarvestAlert,
    HarvestDecision,
    accumulate_gdd,
    compute_urgency,
    cooldown_active,
    cooldown_until_ts,
    evaluate_field_from_db,
    evaluate_harvest,
    evaluate_harvest_alert,
    gdd_daily,
    gdd_from_mean,
    heat_stress_days,
)
from .routing import (
    CorridorConfig,
    PipelineC,
    RouteComparison,
    RouteComparisonResult,
    RouteConfig,
    RoutePoint,
    compare_corridor_routes,
    compare_from_db,
    demo_route_temps,
    eta_hours,
    fuel_estimate_gal,
    geodesic_distance_mi,
    haversine_mi,
    heat_exposure_integral,
    load_corridor_nodes,
    route_spoilage_risk_pct,
    utm_crs_for,
    utm_distance_mi,
)
from .spoilage import (
    COLD_CHAIN_DELTA_F,
    COLD_CHAIN_MIN_BREAK_MIN,
    GA_CROP_SPOILAGE,
    INSULATION_TAU_H,
    SpoilageResult,
    area_weighted_degree_hours,
    degree_hours,
    degree_hours_f,
    detect_cold_chain_breaks,
    estimate_shelf_life_days,
    evaluate_field_spoilage,
    evaluate_route_spoilage,
    evaluate_spoilage,
    spoilage_risk,
    spoilage_risk_pct,
    transit_thermal,
)
from .thresholds import (
    DEFAULT_THRESHOLDS,
    THRESHOLDS,
    crop_thresholds,
    load_thresholds,
)

__all__ = [
    # canopy risk
    "GA_CROP_THRESHOLDS_F",
    "EXCEEDANCE_FULL_H",
    "PERSISTENCE_FULL_H",
    "CANOPY_CAP_F",
    "VPD_COOLING_C",
    "RiskInputs",
    "RiskResult",
    "RiskTier",
    "WorkerSafetyResult",
    "canopy_heat_risk",
    "canopy_risk_score",
    "estimate_canopy_temp",
    "normalized_temp_score",
    "score_field_from_db",
    "tier",
    "vpd_kpa",
    "worker_wbgt_subscore",
    # harvest timing
    "HARVEST_COOLDOWN_H",
    "HARVEST_EXCEEDANCE_THRESHOLD_H",
    "HARVEST_URGENCY_THRESHOLD",
    "GA_CROP_GDD",
    "HarvestAlert",
    "HarvestDecision",
    "accumulate_gdd",
    "compute_urgency",
    "cooldown_active",
    "cooldown_until_ts",
    "evaluate_field_from_db",
    "evaluate_harvest",
    "evaluate_harvest_alert",
    "gdd_daily",
    "gdd_from_mean",
    "heat_stress_days",
    # routing
    "CorridorConfig",
    "RouteComparison",
    "RouteComparisonResult",
    "PipelineC",
    "RouteConfig",
    "RoutePoint",
    "compare_corridor_routes",
    "compare_from_db",
    "demo_route_temps",
    "eta_hours",
    "fuel_estimate_gal",
    "geodesic_distance_mi",
    "haversine_mi",
    "heat_exposure_integral",
    "load_corridor_nodes",
    "route_spoilage_risk_pct",
    "utm_crs_for",
    "utm_distance_mi",
    # spoilage
    "COLD_CHAIN_DELTA_F",
    "COLD_CHAIN_MIN_BREAK_MIN",
    "GA_CROP_SPOILAGE",
    "INSULATION_TAU_H",
    "SpoilageResult",
    "area_weighted_degree_hours",
    "degree_hours",
    "degree_hours_f",
    "detect_cold_chain_breaks",
    "estimate_shelf_life_days",
    "evaluate_field_spoilage",
    "evaluate_route_spoilage",
    "evaluate_spoilage",
    "spoilage_risk",
    "spoilage_risk_pct",
    "transit_thermal",
    # thresholds
    "DEFAULT_THRESHOLDS",
    "THRESHOLDS",
    "crop_thresholds",
    "load_thresholds",
]